name: ecr-build-deploy

on:
  push:
    branches:
      - main # Runs on pushes to the main branch

env:
  AWS_REGION: ca-central-1                  # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ECR_REPOSITORY

permissions:
  id-token: write # Allows GitHub Actions to use OIDC
  contents: read

jobs:
  terragrunt-plan-apply:
    name: terragrunt-plan-apply
    runs-on: ubuntu-latest

    steps:
#      # Step 1: Checkout the repository
#      - name: Checkout repository
#        uses: actions/checkout@v3

#       Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        id: configure_aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: arn:aws:iam::AWS_ACCOUNT_ID:role/GitHubActionsECRAdmin # Replace with your IAM role ARN
          aws-region: ca-central-1 # Replace with your AWS region

#      - name: Gruntwork Terragrunt
#        uses: gruntwork-io/terragrunt-action@v2.1.4

