name: ecr-build-deploy

on:
  push:
    branches:
      - main # Runs on pushes to the main branch

env:
  AWS_REGION: ca-central-1                  # set this to your preferred AWS region, e.g. us-west-1
  # ECR_REPOSITORY: ECR_REPOSITORY

permissions:
  id-token: write # Allows GitHub Actions to use OIDC
  contents: read

jobs:
  terragrunt-plan-apply:
    name: terragrunt-plan-apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::891377081827:role/GitHubActionsECRAdmin #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: 'Terragrunt Plan'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_subcommand: 'plan -auto-approve'

      - name: 'Terragrunt Apply'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_subcommand: 'apply -auto-approve'


