name: ecr-build-deploy

on:
  push:
    branches:
      - main # Runs on pushes to the main branch

permissions:
  id-token: write # Allows GitHub Actions to use OIDC
  contents: read

jobs:
  terraform-plan-apply:
    name: Provision AWS Resources
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        id: configure_aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::AWS_ACCOUNT_ID:role/GitHubActionsECRAdmin # Replace with your IAM role ARN
          aws-region: ca-central-1 # Replace with your AWS region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.10.1
